version: 1

formatters:
  standard:
    format: "[%(levelname)s:%(asctime)s:%(filename)s(%(lineno)s)] %(message)s"
    datefmt: "%d/%m/%Y %H:%M:%S"

handlers:
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./log/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20 # кол-во файлов
    encoding: utf8

loggers:
  <module>:
    level: INFO
    handlers: [info_file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [info_file_handler]
  propagate: yes
