# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\QtProjects\oci\gui\add_order_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1429, 667)
        Dialog.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainArea = QtWidgets.QFrame(Dialog)
        self.mainArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainArea.setObjectName("mainArea")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainArea)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.mainArea)
        self.splitter.setStyleSheet("QSplitter::handle {\n"
"    background: rgb(231, 231, 231);\n"
"}")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.leftArea = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftArea.sizePolicy().hasHeightForWidth())
        self.leftArea.setSizePolicy(sizePolicy)
        self.leftArea.setMinimumSize(QtCore.QSize(540, 0))
        self.leftArea.setMaximumSize(QtCore.QSize(680, 16777215))
        self.leftArea.setStyleSheet("QFrame {\n"
"    background-color: rgb(231, 231, 231);\n"
"}")
        self.leftArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftArea.setObjectName("leftArea")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftArea)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchName = QtWidgets.QLineEdit(self.leftArea)
        self.searchName.setMinimumSize(QtCore.QSize(0, 25))
        self.searchName.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.searchName.setObjectName("searchName")
        self.verticalLayout_3.addWidget(self.searchName)
        self.treeView_1 = QtWidgets.QTreeView(self.leftArea)
        self.treeView_1.setMinimumSize(QtCore.QSize(0, 0))
        self.treeView_1.setStyleSheet("QTreeView {\n"
"    border: 1px solid gray;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"    border-image: url(:icons/vline.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"    border-image: url(:icons/branch-more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"    border-image: url(:icons/branch-end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"        border-image: none;\n"
"        image: url(:icons/branch-closed.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"        border-image: none;\n"
"        image: url(:icons/branch-open.png);\n"
"}")
        self.treeView_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeView_1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView_1.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.treeView_1.setIndentation(20)
        self.treeView_1.setAnimated(True)
        self.treeView_1.setWordWrap(True)
        self.treeView_1.setObjectName("treeView_1")
        self.verticalLayout_3.addWidget(self.treeView_1)
        self.rightArea = QtWidgets.QFrame(self.splitter)
        self.rightArea.setMinimumSize(QtCore.QSize(850, 0))
        self.rightArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightArea.setObjectName("rightArea")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rightArea)
        self.verticalLayout_4.setContentsMargins(20, 10, 10, 10)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.orderName = QtWidgets.QLineEdit(self.rightArea)
        self.orderName.setMinimumSize(QtCore.QSize(0, 25))
        self.orderName.setStyleSheet("")
        self.orderName.setObjectName("orderName")
        self.verticalLayout_4.addWidget(self.orderName)
        self.frame = QtWidgets.QFrame(self.rightArea)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame)
        self.doubleSpinBox.setEnabled(False)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.frame)
        self.treeView_2 = QtWidgets.QTreeView(self.rightArea)
        self.treeView_2.setStyleSheet("QTreeView {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"    border-image: url(:icons/vline.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"    border-image: url(:icons/branch-more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"    border-image: url(:icons/branch-end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"        border-image: none;\n"
"        image: url(:icons/branch-closed.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"        border-image: none;\n"
"        image: url(:icons/branch-open.png);\n"
"}")
        self.treeView_2.setAnimated(True)
        self.treeView_2.setWordWrap(True)
        self.treeView_2.setObjectName("treeView_2")
        self.verticalLayout_4.addWidget(self.treeView_2)
        self.ingotsView = QtWidgets.QListView(self.rightArea)
        self.ingotsView.setMinimumSize(QtCore.QSize(0, 195))
        self.ingotsView.setMaximumSize(QtCore.QSize(16777215, 195))
        self.ingotsView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ingotsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ingotsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ingotsView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ingotsView.setProperty("showDropIndicator", False)
        self.ingotsView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ingotsView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.ingotsView.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.ingotsView.setFlow(QtWidgets.QListView.LeftToRight)
        self.ingotsView.setObjectName("ingotsView")
        self.verticalLayout_4.addWidget(self.ingotsView)
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.mainArea)
        self.buttonArea = QtWidgets.QFrame(Dialog)
        self.buttonArea.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonArea.setMaximumSize(QtCore.QSize(16777215, 40))
        self.buttonArea.setStyleSheet("QFrame {\n"
"    background-color: rgb(231, 231, 231);\n"
"}")
        self.buttonArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttonArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonArea.setObjectName("buttonArea")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttonArea)
        self.horizontalLayout_2.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.add = QtWidgets.QPushButton(self.buttonArea)
        self.add.setMinimumSize(QtCore.QSize(80, 0))
        self.add.setObjectName("add")
        self.horizontalLayout_2.addWidget(self.add)
        self.pushButton = QtWidgets.QPushButton(self.buttonArea)
        self.pushButton.setEnabled(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.cancel = QtWidgets.QPushButton(self.buttonArea)
        self.cancel.setMinimumSize(QtCore.QSize(80, 0))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.verticalLayout.addWidget(self.buttonArea)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Новый заказ"))
        self.searchName.setPlaceholderText(_translate("Dialog", "Введите название изделия..."))
        self.orderName.setPlaceholderText(_translate("Dialog", "Введите название заказа..."))
        self.label.setText(_translate("Dialog", "Толщина реза:"))
        self.add.setText(_translate("Dialog", "Добавить"))
        self.pushButton.setText(_translate("Dialog", "Рассчитать"))
        self.cancel.setText(_translate("Dialog", "Отмена"))
