# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\QtProjects\oci\gui\add_article_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(408, 135)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(10, 10, 10, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.parameters = QtWidgets.QGroupBox(Dialog)
        self.parameters.setObjectName("parameters")
        self.gridLayout = QtWidgets.QGridLayout(self.parameters)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_1 = QtWidgets.QLabel(self.parameters)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.regnum = QtWidgets.QLineEdit(self.parameters)
        self.regnum.setClearButtonEnabled(True)
        self.regnum.setObjectName("regnum")
        self.gridLayout.addWidget(self.regnum, 0, 1, 1, 1)
        self.name = QtWidgets.QLineEdit(self.parameters)
        self.name.setClearButtonEnabled(True)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.parameters)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.parameters)
        self.button_frame = QtWidgets.QFrame(Dialog)
        self.button_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.add = QtWidgets.QPushButton(self.button_frame)
        self.add.setMinimumSize(QtCore.QSize(90, 0))
        self.add.setObjectName("add")
        self.horizontalLayout.addWidget(self.add)
        self.cancel = QtWidgets.QPushButton(self.button_frame)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addWidget(self.button_frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление изделия"))
        self.parameters.setTitle(_translate("Dialog", "Параметры изделия"))
        self.label_1.setText(_translate("Dialog", "Номер ведомости:"))
        self.regnum.setPlaceholderText(_translate("Dialog", "Введите номер ведомости..."))
        self.name.setPlaceholderText(_translate("Dialog", "Введите название продукции..."))
        self.label_3.setText(_translate("Dialog", "Название изделия:"))
        self.add.setText(_translate("Dialog", "Добавить"))
        self.cancel.setText(_translate("Dialog", "Отмена"))
