# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\QtProjects\oci\gui\edit_order_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1395, 650)
        Dialog.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_area = QtWidgets.QFrame(Dialog)
        self.main_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_area.setObjectName("main_area")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_area)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.main_area)
        self.splitter.setStyleSheet("QSplitter::handle {\n"
"    background-image: url(:/icons/splitter.png);\n"
"}")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(59)
        self.splitter.setObjectName("splitter")
        self.catalog_area = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catalog_area.sizePolicy().hasHeightForWidth())
        self.catalog_area.setSizePolicy(sizePolicy)
        self.catalog_area.setMinimumSize(QtCore.QSize(400, 0))
        self.catalog_area.setMaximumSize(QtCore.QSize(400, 16777215))
        self.catalog_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.catalog_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.catalog_area.setObjectName("catalog_area")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.catalog_area)
        self.verticalLayout_3.setContentsMargins(10, 10, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tip_1 = QtWidgets.QLabel(self.catalog_area)
        self.tip_1.setObjectName("tip_1")
        self.verticalLayout_3.addWidget(self.tip_1)
        self.search = QtWidgets.QLineEdit(self.catalog_area)
        self.search.setMinimumSize(QtCore.QSize(0, 25))
        self.search.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.search.setObjectName("search")
        self.verticalLayout_3.addWidget(self.search)
        self.catalog_view = QtWidgets.QTreeView(self.catalog_area)
        self.catalog_view.setMinimumSize(QtCore.QSize(0, 540))
        self.catalog_view.setStyleSheet("QTreeView {\n"
"    border: 1px solid gray;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"    border-image: url(:icons/vline.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"    border-image: url(:icons/branch-more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"    border-image: url(:icons/branch-end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"        border-image: none;\n"
"        image: url(:icons/branch-closed.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"        border-image: none;\n"
"        image: url(:icons/branch-open.png);\n"
"}")
        self.catalog_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.catalog_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.catalog_view.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.catalog_view.setIndentation(20)
        self.catalog_view.setAnimated(True)
        self.catalog_view.setWordWrap(True)
        self.catalog_view.setExpandsOnDoubleClick(False)
        self.catalog_view.setObjectName("catalog_view")
        self.verticalLayout_3.addWidget(self.catalog_view)
        self.complects_area = QtWidgets.QFrame(self.splitter)
        self.complects_area.setMinimumSize(QtCore.QSize(850, 0))
        self.complects_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.complects_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.complects_area.setObjectName("complects_area")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.complects_area)
        self.verticalLayout_4.setContentsMargins(0, 10, 10, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tip_2 = QtWidgets.QLabel(self.complects_area)
        self.tip_2.setMinimumSize(QtCore.QSize(0, 48))
        self.tip_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tip_2.setObjectName("tip_2")
        self.verticalLayout_4.addWidget(self.tip_2)
        self.complects_view = QtWidgets.QTreeView(self.complects_area)
        self.complects_view.setMinimumSize(QtCore.QSize(0, 540))
        self.complects_view.setStyleSheet("QTreeView {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"    border-image: url(:icons/vline.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"    border-image: url(:icons/branch-more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"    border-image: url(:icons/branch-end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"        border-image: none;\n"
"        image: url(:icons/branch-closed.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"        border-image: none;\n"
"        image: url(:icons/branch-open.png);\n"
"}")
        self.complects_view.setAnimated(True)
        self.complects_view.setWordWrap(True)
        self.complects_view.setExpandsOnDoubleClick(False)
        self.complects_view.setObjectName("complects_view")
        self.verticalLayout_4.addWidget(self.complects_view)
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.main_area)
        self.button_area = QtWidgets.QFrame(Dialog)
        self.button_area.setMinimumSize(QtCore.QSize(0, 40))
        self.button_area.setMaximumSize(QtCore.QSize(16777215, 40))
        self.button_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.button_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_area.setObjectName("button_area")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.button_area)
        self.horizontalLayout_2.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.save = QtWidgets.QPushButton(self.button_area)
        self.save.setMinimumSize(QtCore.QSize(80, 0))
        self.save.setObjectName("save")
        self.horizontalLayout_2.addWidget(self.save)
        self.verticalLayout.addWidget(self.button_area)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Редактирование заказа"))
        self.tip_1.setText(_translate("Dialog", "1. Выберите заготовки и добавьте их в заказ"))
        self.search.setPlaceholderText(_translate("Dialog", "Введите название изделия..."))
        self.tip_2.setText(_translate("Dialog", "2. Проверьте и при необходимости скорректируйте состав заказа (количество и приоритет заготовок)"))
        self.save.setText(_translate("Dialog", "Сохранить"))
import application_rc
