# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\QtProjects\oci\gui\finish_step_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 486)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_area = QtWidgets.QFrame(Dialog)
        self.main_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_area.setObjectName("main_area")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_area)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.right_area = QtWidgets.QFrame(self.main_area)
        self.right_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_area.setObjectName("right_area")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_area)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.leftover_size = QtWidgets.QGroupBox(self.right_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftover_size.sizePolicy().hasHeightForWidth())
        self.leftover_size.setSizePolicy(sizePolicy)
        self.leftover_size.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftover_size.setObjectName("leftover_size")
        self.formLayout_2 = QtWidgets.QFormLayout(self.leftover_size)
        self.formLayout_2.setContentsMargins(10, 5, 10, 10)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.leftover_length_label = QtWidgets.QLabel(self.leftover_size)
        self.leftover_length_label.setMinimumSize(QtCore.QSize(70, 0))
        self.leftover_length_label.setObjectName("leftover_length_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.leftover_length_label)
        self.leftover_leigth = QtWidgets.QDoubleSpinBox(self.leftover_size)
        self.leftover_leigth.setMinimum(1.0)
        self.leftover_leigth.setMaximum(1200.0)
        self.leftover_leigth.setObjectName("leftover_leigth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leftover_leigth)
        self.leftover_width_label = QtWidgets.QLabel(self.leftover_size)
        self.leftover_width_label.setMinimumSize(QtCore.QSize(70, 0))
        self.leftover_width_label.setObjectName("leftover_width_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.leftover_width_label)
        self.leftover_width = QtWidgets.QDoubleSpinBox(self.leftover_size)
        self.leftover_width.setMinimum(1.0)
        self.leftover_width.setMaximum(1200.0)
        self.leftover_width.setObjectName("leftover_width")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leftover_width)
        self.leftover = QtWidgets.QPushButton(self.leftover_size)
        self.leftover.setMaximumSize(QtCore.QSize(130, 16777215))
        self.leftover.setObjectName("leftover")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leftover)
        self.verticalLayout_4.addWidget(self.leftover_size)
        self.leftoversTable = QtWidgets.QTableView(self.right_area)
        self.leftoversTable.setMinimumSize(QtCore.QSize(0, 300))
        self.leftoversTable.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-top: none;\n"
"}")
        self.leftoversTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.leftoversTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.leftoversTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.leftoversTable.setObjectName("leftoversTable")
        self.leftoversTable.verticalHeader().setCascadingSectionResizes(True)
        self.leftoversTable.verticalHeader().setDefaultSectionSize(21)
        self.verticalLayout_4.addWidget(self.leftoversTable)
        self.horizontalLayout.addWidget(self.right_area)
        self.verticalLayout.addWidget(self.main_area)
        self.button_area = QtWidgets.QFrame(Dialog)
        self.button_area.setMinimumSize(QtCore.QSize(0, 0))
        self.button_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.button_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_area.setObjectName("button_area")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.button_area)
        self.horizontalLayout_2.setContentsMargins(0, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.finish = QtWidgets.QPushButton(self.button_area)
        self.finish.setMinimumSize(QtCore.QSize(80, 0))
        self.finish.setObjectName("finish")
        self.horizontalLayout_2.addWidget(self.finish)
        self.verticalLayout.addWidget(self.button_area)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Завершение заказа"))
        self.leftover_size.setTitle(_translate("Dialog", "Параметры остатка"))
        self.leftover_length_label.setText(_translate("Dialog", "Длина:    "))
        self.leftover_leigth.setSuffix(_translate("Dialog", " мм"))
        self.leftover_width_label.setText(_translate("Dialog", "Ширина:    "))
        self.leftover_width.setSuffix(_translate("Dialog", " мм"))
        self.leftover.setText(_translate("Dialog", "Добавить остаток"))
        self.finish.setText(_translate("Dialog", "Завершить"))
