# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\QtProjects\oci\gui\full_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 529)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.map = QtWidgets.QGraphicsView(Dialog)
        self.map.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.map.setObjectName("map")
        self.verticalLayout.addWidget(self.map)
        self.main_area = QtWidgets.QFrame(Dialog)
        self.main_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_area.setObjectName("main_area")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_area)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_1 = QtWidgets.QLabel(self.main_area)
        self.icon_1.setMaximumSize(QtCore.QSize(40, 40))
        self.icon_1.setText("")
        self.icon_1.setPixmap(QtGui.QPixmap(":/icons/scissors.png"))
        self.icon_1.setScaledContents(True)
        self.icon_1.setObjectName("icon_1")
        self.horizontalLayout.addWidget(self.icon_1)
        self.label_1 = QtWidgets.QLabel(self.main_area)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.line = QtWidgets.QFrame(self.main_area)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.icon_2 = QtWidgets.QLabel(self.main_area)
        self.icon_2.setMaximumSize(QtCore.QSize(40, 40))
        self.icon_2.setText("")
        self.icon_2.setPixmap(QtGui.QPixmap(":/icons/h-roll.png"))
        self.icon_2.setScaledContents(True)
        self.icon_2.setObjectName("icon_2")
        self.horizontalLayout.addWidget(self.icon_2)
        self.label_2 = QtWidgets.QLabel(self.main_area)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(self.main_area)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.icon_3 = QtWidgets.QLabel(self.main_area)
        self.icon_3.setMinimumSize(QtCore.QSize(0, 0))
        self.icon_3.setMaximumSize(QtCore.QSize(40, 40))
        self.icon_3.setText("")
        self.icon_3.setPixmap(QtGui.QPixmap(":/icons/v-roll.png"))
        self.icon_3.setScaledContents(True)
        self.icon_3.setObjectName("icon_3")
        self.horizontalLayout.addWidget(self.icon_3)
        self.label_3 = QtWidgets.QLabel(self.main_area)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.line_3 = QtWidgets.QFrame(self.main_area)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.icon_4 = QtWidgets.QLabel(self.main_area)
        self.icon_4.setMinimumSize(QtCore.QSize(45, 0))
        self.icon_4.setMaximumSize(QtCore.QSize(45, 40))
        self.icon_4.setText("")
        self.icon_4.setPixmap(QtGui.QPixmap(":/icons/blueprint.png"))
        self.icon_4.setScaledContents(True)
        self.icon_4.setObjectName("icon_4")
        self.horizontalLayout.addWidget(self.icon_4)
        self.label_4 = QtWidgets.QLabel(self.main_area)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.main_area)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Карта: полноэкранный режим"))
        self.label_1.setText(_translate("Dialog", "Операция\n"
"раскроя"))
        self.label_2.setText(_translate("Dialog", "Операция\n"
"горизон-го\n"
"проката"))
        self.label_3.setText(_translate("Dialog", "Операция\n"
"вертик-го\n"
"проката"))
        self.label_4.setText(_translate("Dialog", "Операция\n"
"упаковки"))
import application_rc
