# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\QtProjects\oci\gui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 704)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/kras-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pageBar = QtWidgets.QFrame(self.centralWidget)
        self.pageBar.setStyleSheet("QFrame {\n"
"    background-color: rgb(225, 225, 225);\n"
"}")
        self.pageBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pageBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pageBar.setObjectName("pageBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pageBar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.information = QtWidgets.QPushButton(self.pageBar)
        self.information.setEnabled(True)
        self.information.setMinimumSize(QtCore.QSize(100, 30))
        self.information.setMaximumSize(QtCore.QSize(16777215, 30))
        self.information.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(225, 225, 225);\n"
"    padding: 0px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 235, 235);\n"
"    border-bottom: 3px solid gray;\n"
"    font-weight: 800;\n"
"    padding-top: 3px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(245, 245, 245);\n"
"    border-bottom: 3px solid gray;\n"
"    font-weight: 800;\n"
"    padding-top: 3px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-bottom: 3px solid black;\n"
"    padding-top: 3px;\n"
"    font-weight: 800;\n"
"}")
        self.information.setCheckable(True)
        self.information.setChecked(True)
        self.information.setAutoExclusive(True)
        self.information.setObjectName("information")
        self.horizontalLayout_3.addWidget(self.information)
        self.chart = QtWidgets.QPushButton(self.pageBar)
        self.chart.setEnabled(False)
        self.chart.setMinimumSize(QtCore.QSize(100, 30))
        self.chart.setMaximumSize(QtCore.QSize(16777215, 30))
        self.chart.setStyleSheet("QPushButton:disabled {\n"
"    border: none;\n"
"    background-color: rgb(225, 225, 225);\n"
"    padding: 0px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:disabled:checked {\n"
"    border-bottom: 3px solid black;\n"
"    background-color: rgb(225, 225, 225);\n"
"    padding-top: 3px;\n"
"    font-weight: 800;\n"
"    color: black;\n"
"}")
        self.chart.setCheckable(True)
        self.chart.setAutoExclusive(True)
        self.chart.setObjectName("chart")
        self.horizontalLayout_3.addWidget(self.chart)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.pageBar)
        self.topBar = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topBar.sizePolicy().hasHeightForWidth())
        self.topBar.setSizePolicy(sizePolicy)
        self.topBar.setMinimumSize(QtCore.QSize(0, 80))
        self.topBar.setStyleSheet("QFrame {\n"
"    background-color: rgb(225, 225, 225);\n"
"}")
        self.topBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBar.setObjectName("topBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topBar)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newOrder = QtWidgets.QToolButton(self.topBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newOrder.sizePolicy().hasHeightForWidth())
        self.newOrder.setSizePolicy(sizePolicy)
        self.newOrder.setMinimumSize(QtCore.QSize(50, 60))
        self.newOrder.setMaximumSize(QtCore.QSize(16777215, 80))
        self.newOrder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newOrder.setStyleSheet("QToolButton {\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 3px;\n"
"    padding-top: 2px;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(189, 189, 189);\n"
"    padding-left: 0px;\n"
"    padding-top: 2px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newOrder.setIcon(icon1)
        self.newOrder.setIconSize(QtCore.QSize(30, 30))
        self.newOrder.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.newOrder.setObjectName("newOrder")
        self.horizontalLayout_2.addWidget(self.newOrder)
        self.newIngot = QtWidgets.QToolButton(self.topBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newIngot.sizePolicy().hasHeightForWidth())
        self.newIngot.setSizePolicy(sizePolicy)
        self.newIngot.setMinimumSize(QtCore.QSize(50, 0))
        self.newIngot.setMaximumSize(QtCore.QSize(16777215, 80))
        self.newIngot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newIngot.setStyleSheet("QToolButton {\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 3px;\n"
"    padding-top: 2px;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(189, 189, 189);\n"
"    padding-left: 0px;\n"
"    padding-top: 2px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/ingot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newIngot.setIcon(icon2)
        self.newIngot.setIconSize(QtCore.QSize(30, 30))
        self.newIngot.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.newIngot.setObjectName("newIngot")
        self.horizontalLayout_2.addWidget(self.newIngot)
        self.line_1 = QtWidgets.QFrame(self.topBar)
        self.line_1.setMinimumSize(QtCore.QSize(0, 0))
        self.line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_1.setLineWidth(1)
        self.line_1.setObjectName("line_1")
        self.horizontalLayout_2.addWidget(self.line_1)
        self.catalog = QtWidgets.QToolButton(self.topBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catalog.sizePolicy().hasHeightForWidth())
        self.catalog.setSizePolicy(sizePolicy)
        self.catalog.setMinimumSize(QtCore.QSize(50, 60))
        self.catalog.setMaximumSize(QtCore.QSize(16777215, 80))
        self.catalog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.catalog.setStyleSheet("QToolButton {\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 3px;\n"
"    padding-top: 2px;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(189, 189, 189);\n"
"    padding-left: 0px;\n"
"    padding-top: 2px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.catalog.setIcon(icon3)
        self.catalog.setIconSize(QtCore.QSize(40, 30))
        self.catalog.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.catalog.setObjectName("catalog")
        self.horizontalLayout_2.addWidget(self.catalog)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.settings = QtWidgets.QToolButton(self.topBar)
        self.settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings.setStyleSheet("QToolButton {\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-radius: 3px;\n"
"    padding-top: 2px;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(210, 210, 210);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(189, 189, 189);\n"
"    padding-left: 0px;\n"
"    padding-top: 2px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings.setIcon(icon4)
        self.settings.setIconSize(QtCore.QSize(40, 30))
        self.settings.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.settings.setObjectName("settings")
        self.horizontalLayout_2.addWidget(self.settings)
        self.verticalLayout.addWidget(self.topBar)
        self.mainArea = QtWidgets.QStackedWidget(self.centralWidget)
        self.mainArea.setStyleSheet("")
        self.mainArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainArea.setObjectName("mainArea")
        self.observerPage = QtWidgets.QWidget()
        self.observerPage.setObjectName("observerPage")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.observerPage)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenu_1 = QtWidgets.QFrame(self.observerPage)
        self.leftMenu_1.setMaximumSize(QtCore.QSize(400, 16777215))
        self.leftMenu_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenu_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenu_1.setObjectName("leftMenu_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenu_1)
        self.verticalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchNumber = QtWidgets.QLineEdit(self.leftMenu_1)
        self.searchNumber.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchNumber.sizePolicy().hasHeightForWidth())
        self.searchNumber.setSizePolicy(sizePolicy)
        self.searchNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.searchNumber.setMaximumSize(QtCore.QSize(16777215, 30))
        self.searchNumber.setClearButtonEnabled(True)
        self.searchNumber.setObjectName("searchNumber")
        self.verticalLayout_2.addWidget(self.searchNumber)
        self.searchType = QtWidgets.QComboBox(self.leftMenu_1)
        self.searchType.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchType.sizePolicy().hasHeightForWidth())
        self.searchType.setSizePolicy(sizePolicy)
        self.searchType.setMinimumSize(QtCore.QSize(0, 30))
        self.searchType.setMaximumSize(QtCore.QSize(16777215, 30))
        self.searchType.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchType.setObjectName("searchType")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.searchType.addItem("")
        self.verticalLayout_2.addWidget(self.searchType)
        self.searchResult_1 = QtWidgets.QListView(self.leftMenu_1)
        self.searchResult_1.setObjectName("searchResult_1")
        self.verticalLayout_2.addWidget(self.searchResult_1)
        self.horizontalLayout.addWidget(self.leftMenu_1)
        self.orderInformationArea = QtWidgets.QStackedWidget(self.observerPage)
        self.orderInformationArea.setObjectName("orderInformationArea")
        self.defaultPage = QtWidgets.QWidget()
        self.defaultPage.setStyleSheet("QWidget#defaultPage {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.defaultPage.setObjectName("defaultPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.defaultPage)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.defaultLabel = QtWidgets.QLabel(self.defaultPage)
        self.defaultLabel.setStyleSheet("border: 2px dashed rgb(231, 231, 231);\n"
"border-radius: 10px;")
        self.defaultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.defaultLabel.setObjectName("defaultLabel")
        self.verticalLayout_3.addWidget(self.defaultLabel)
        self.orderInformationArea.addWidget(self.defaultPage)
        self.informationPage = QtWidgets.QWidget()
        self.informationPage.setStyleSheet("QWidget#informationPage {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.informationPage.setObjectName("informationPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.informationPage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.informationPage)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    padding-left: 10px;\n"
"    background-color: rgb(225, 225, 225);\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(self.informationPage)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    padding-left: 20px;\n"
"    padding-right: 7px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    margin-top: 5px;\n"
"    margin-bottom: 5px;\n"
"    background: rgb(255, 255, 255);\n"
"    width: 7px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(180, 180, 180);\n"
"    min-height: 30px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(255, 145, 67);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: rgb(223, 124, 59);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 681, 1278))
        self.scrollAreaWidgetContents.setStyleSheet("* {\n"
"    margin-right: 7px;\n"
"}\n"
"\n"
"QScrollArea, QFrame, QLabel, QWidget#scrollAreaWidgetContents, QWidget#scrollAreaWidgetContents_2, QWidget#scrollAreaWidgetContents_3 {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel {\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"    ")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.complectsFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.complectsFrame.setStyleSheet("* {\n"
"    margin-right: 0px;\n"
"}")
        self.complectsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.complectsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.complectsFrame.setObjectName("complectsFrame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.complectsFrame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.complectsFrame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: rgb(234, 234, 234);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.saveComplect = QtWidgets.QPushButton(self.complectsFrame)
        self.saveComplect.setMinimumSize(QtCore.QSize(120, 40))
        self.saveComplect.setMaximumSize(QtCore.QSize(120, 40))
        self.saveComplect.setStyleSheet("QPushButton {\n"
"    margin-top: 10px;\n"
"    border: none;\n"
"    background-color: rgb(234, 234, 234);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.saveComplect.setObjectName("saveComplect")
        self.horizontalLayout_8.addWidget(self.saveComplect)
        self.saveComplectAndRecreate = QtWidgets.QPushButton(self.complectsFrame)
        self.saveComplectAndRecreate.setMinimumSize(QtCore.QSize(120, 40))
        self.saveComplectAndRecreate.setMaximumSize(QtCore.QSize(120, 40))
        self.saveComplectAndRecreate.setStyleSheet("QPushButton {\n"
"    margin-top: 10px;\n"
"    margin-right: 7px;\n"
"    border: none;\n"
"    background-color: rgb(234, 234, 234);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.saveComplectAndRecreate.setObjectName("saveComplectAndRecreate")
        self.horizontalLayout_8.addWidget(self.saveComplectAndRecreate)
        self.verticalLayout_4.addWidget(self.complectsFrame)
        self.complectsView = QtWidgets.QTreeView(self.scrollAreaWidgetContents)
        self.complectsView.setMinimumSize(QtCore.QSize(0, 300))
        self.complectsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.complectsView.setStyleSheet("QTreeView {\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    background-color: rgb(231, 231, 231);\n"
"    padding-left: 10px;\n"
"    border: 1px solid gray;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    border-top: none;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"    border-image: url(:icons/vline.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"    border-image: url(:icons/branch-more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"    border-image: url(:icons/branch-end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"        border-image: none;\n"
"        image: url(:icons/branch-closed.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"        border-image: none;\n"
"        image: url(:icons/branch-open.png);\n"
"}")
        self.complectsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.complectsView.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.complectsView.setAlternatingRowColors(False)
        self.complectsView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.complectsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.complectsView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.complectsView.setAnimated(True)
        self.complectsView.setObjectName("complectsView")
        self.verticalLayout_4.addWidget(self.complectsView)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(234, 234, 234);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.ingotsView = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.ingotsView.setMinimumSize(QtCore.QSize(0, 195))
        self.ingotsView.setMaximumSize(QtCore.QSize(16777215, 195))
        self.ingotsView.setFrameShape(QtWidgets.QFrame.Box)
        self.ingotsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ingotsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ingotsView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ingotsView.setProperty("showDropIndicator", False)
        self.ingotsView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ingotsView.setFlow(QtWidgets.QListView.LeftToRight)
        self.ingotsView.setObjectName("ingotsView")
        self.verticalLayout_4.addWidget(self.ingotsView)
        self.detailedPlanFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.detailedPlanFrame.setStyleSheet("* {\n"
"    margin-right: 0px;\n"
"}")
        self.detailedPlanFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.detailedPlanFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detailedPlanFrame.setObjectName("detailedPlanFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.detailedPlanFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.detailedPlanFrame)
        self.label_7.setMinimumSize(QtCore.QSize(0, 40))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: rgb(234, 234, 234);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.recalculate = QtWidgets.QPushButton(self.detailedPlanFrame)
        self.recalculate.setMinimumSize(QtCore.QSize(120, 40))
        self.recalculate.setMaximumSize(QtCore.QSize(120, 40))
        self.recalculate.setStyleSheet("QPushButton {\n"
"    margin-top: 10px;\n"
"    border: none;\n"
"    background-color: rgb(234, 234, 234);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.recalculate.setObjectName("recalculate")
        self.horizontalLayout_5.addWidget(self.recalculate)
        self.fullScreen = QtWidgets.QPushButton(self.detailedPlanFrame)
        self.fullScreen.setMinimumSize(QtCore.QSize(120, 40))
        self.fullScreen.setMaximumSize(QtCore.QSize(120, 40))
        self.fullScreen.setStyleSheet("QPushButton {\n"
"    margin-top: 10px;\n"
"    border: none;\n"
"    background-color: rgb(234, 234, 234);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.fullScreen.setObjectName("fullScreen")
        self.horizontalLayout_5.addWidget(self.fullScreen)
        self.detailedPlan = QtWidgets.QPushButton(self.detailedPlanFrame)
        self.detailedPlan.setMinimumSize(QtCore.QSize(120, 40))
        self.detailedPlan.setMaximumSize(QtCore.QSize(120, 40))
        self.detailedPlan.setStyleSheet("QPushButton {\n"
"    margin-top: 10px;\n"
"    margin-right: 7px;\n"
"    border: none;\n"
"    background-color: rgb(234, 234, 234);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.detailedPlan.setObjectName("detailedPlan")
        self.horizontalLayout_5.addWidget(self.detailedPlan)
        self.verticalLayout_4.addWidget(self.detailedPlanFrame)
        self.graphicsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 500))
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_4.addWidget(self.graphicsView)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMinimumSize(QtCore.QSize(0, 40))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: rgb(234, 234, 234);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.orderInformationArea.addWidget(self.informationPage)
        self.horizontalLayout.addWidget(self.orderInformationArea)
        self.mainArea.addWidget(self.observerPage)
        self.chartPage = QtWidgets.QWidget()
        self.chartPage.setObjectName("chartPage")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.chartPage)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.leftMenu_2 = QtWidgets.QFrame(self.chartPage)
        self.leftMenu_2.setMinimumSize(QtCore.QSize(400, 0))
        self.leftMenu_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.leftMenu_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenu_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenu_2.setObjectName("leftMenu_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.leftMenu_2)
        self.verticalLayout_7.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.searchName = QtWidgets.QLineEdit(self.leftMenu_2)
        self.searchName.setEnabled(False)
        self.searchName.setMinimumSize(QtCore.QSize(0, 30))
        self.searchName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.searchName.setClearButtonEnabled(True)
        self.searchName.setObjectName("searchName")
        self.verticalLayout_7.addWidget(self.searchName)
        self.searchResult_2 = QtWidgets.QScrollArea(self.leftMenu_2)
        self.searchResult_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchResult_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.searchResult_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.searchResult_2.setWidgetResizable(True)
        self.searchResult_2.setObjectName("searchResult_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 83, 30))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, -1, 7, -1)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.searchResult_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.searchResult_2)
        self.closeOrder = QtWidgets.QPushButton(self.leftMenu_2)
        self.closeOrder.setMinimumSize(QtCore.QSize(0, 40))
        self.closeOrder.setObjectName("closeOrder")
        self.verticalLayout_7.addWidget(self.closeOrder)
        self.horizontalLayout_4.addWidget(self.leftMenu_2)
        self.chartArea = QtWidgets.QFrame(self.chartPage)
        self.chartArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chartArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chartArea.setObjectName("chartArea")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.chartArea)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.depthLine = QtWidgets.QScrollArea(self.chartArea)
        self.depthLine.setMaximumSize(QtCore.QSize(16777215, 47))
        self.depthLine.setStyleSheet("QScrollArea {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(255, 255, 255);\n"
"    height: 7px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(180, 180, 180);\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(255, 145, 67);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background-color: rgb(223, 124, 59);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"    width: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"    width: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.depthLine.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.depthLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.depthLine.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.depthLine.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.depthLine.setWidgetResizable(True)
        self.depthLine.setObjectName("depthLine")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 98, 42))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sourcePlate = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourcePlate.sizePolicy().hasHeightForWidth())
        self.sourcePlate.setSizePolicy(sizePolicy)
        self.sourcePlate.setMinimumSize(QtCore.QSize(80, 40))
        self.sourcePlate.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sourcePlate.setFont(font)
        self.sourcePlate.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(225, 225, 225);\n"
"    width: 80px;\n"
"    height: 40px;\n"
"    padding: 0px;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 235, 235);\n"
"    border-bottom: 3px solid gray;\n"
"    font-weight: 800;\n"
"    padding-top: 3px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(245, 245, 245);\n"
"    border-bottom: 3px solid gray;\n"
"    font-weight: 800;\n"
"    padding-top: 3px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(225, 225, 225);\n"
"    border-bottom: 3px solid black;\n"
"    padding-top: 3px;\n"
"    font-weight: 800;\n"
"}")
        self.sourcePlate.setCheckable(True)
        self.sourcePlate.setChecked(True)
        self.sourcePlate.setAutoExclusive(True)
        self.sourcePlate.setObjectName("sourcePlate")
        self.horizontalLayout_6.addWidget(self.sourcePlate)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.depthLine.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.addWidget(self.depthLine)
        self.horizontalLayout_4.addWidget(self.chartArea)
        self.mainArea.addWidget(self.chartPage)
        self.verticalLayout.addWidget(self.mainArea)
        self.mainArea.raise_()
        self.topBar.raise_()
        self.pageBar.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.mainArea.setCurrentIndex(0)
        self.orderInformationArea.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Раскрой слитка"))
        self.information.setText(_translate("MainWindow", "Заказы"))
        self.chart.setText(_translate("MainWindow", "Карта раскроя"))
        self.newOrder.setText(_translate("MainWindow", "Новый\n"
"заказ"))
        self.newIngot.setText(_translate("MainWindow", "Новый\n"
"слиток"))
        self.catalog.setText(_translate("MainWindow", "Cправочник\n"
"заготовок"))
        self.settings.setText(_translate("MainWindow", "Настройки\n"
"приложения"))
        self.searchNumber.setPlaceholderText(_translate("MainWindow", "Номер заказа..."))
        self.searchType.setItemText(0, _translate("MainWindow", "Все заказы"))
        self.searchType.setItemText(1, _translate("MainWindow", "В процессе"))
        self.searchType.setItemText(2, _translate("MainWindow", "В ожидании раскроя"))
        self.searchType.setItemText(3, _translate("MainWindow", "Не начатые"))
        self.searchType.setItemText(4, _translate("MainWindow", "Завершённые"))
        self.defaultLabel.setText(_translate("MainWindow", "Заказ не выбран"))
        self.label.setText(_translate("MainWindow", "Номер заказа"))
        self.label_2.setText(_translate("MainWindow", "Выбранные заготовки"))
        self.saveComplect.setText(_translate("MainWindow", "Сохранить"))
        self.saveComplectAndRecreate.setText(_translate("MainWindow", "Сохранить\n"
"и пересчитать"))
        self.label_3.setText(_translate("MainWindow", "Выбранные слитки"))
        self.label_7.setText(_translate("MainWindow", "Карта раскроя"))
        self.recalculate.setText(_translate("MainWindow", "Пересчитать"))
        self.fullScreen.setText(_translate("MainWindow", "На весь экран"))
        self.detailedPlan.setText(_translate("MainWindow", "Перейти к плану"))
        self.label_5.setText(_translate("MainWindow", "Статистика по заказу"))
        self.label_6.setText(_translate("MainWindow", "Выход годного:\n"
"\n"
"Готовых деталей:\n"
"Неукомплектованных деталей:\n"
"\n"
"Дефектов раскроя:\n"
"Забракованных деталей:"))
        self.searchName.setPlaceholderText(_translate("MainWindow", "Название детали..."))
        self.closeOrder.setText(_translate("MainWindow", "Завершить заказ"))
        self.sourcePlate.setText(_translate("MainWindow", "Карта\n"
"раскроя"))
import application_rc
