# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\QtProjects\oci\gui\storage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(620, 690)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listView_3 = QtWidgets.QListView(Dialog)
        self.listView_3.setMinimumSize(QtCore.QSize(0, 195))
        self.listView_3.setMaximumSize(QtCore.QSize(16777215, 195))
        self.listView_3.setStyleSheet("QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    height: 10px;\n"
"    background-color: rgb(205,116,61);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background-color: rgb(231, 128, 69);\n"
"}\n"
"\n"
"QScrollBar::handle:pressed {\n"
"    background-color: rgb(231, 128, 69);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal, QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar:left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"")
        self.listView_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listView_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_3.setProperty("showDropIndicator", False)
        self.listView_3.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listView_3.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listView_3.setFlow(QtWidgets.QListView.LeftToRight)
        self.listView_3.setObjectName("listView_3")
        self.verticalLayout.addWidget(self.listView_3)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listView_2 = QtWidgets.QListView(Dialog)
        self.listView_2.setMinimumSize(QtCore.QSize(0, 195))
        self.listView_2.setMaximumSize(QtCore.QSize(16777215, 195))
        self.listView_2.setStyleSheet("QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    height: 10px;\n"
"    background-color: rgb(205,116,61);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background-color: rgb(231, 128, 69);\n"
"}\n"
"\n"
"QScrollBar::handle:pressed {\n"
"    background-color: rgb(231, 128, 69);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal, QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar:left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"")
        self.listView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listView_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_2.setProperty("showDropIndicator", False)
        self.listView_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listView_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listView_2.setFlow(QtWidgets.QListView.LeftToRight)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout.addWidget(self.listView_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setMinimumSize(QtCore.QSize(0, 195))
        self.listView.setMaximumSize(QtCore.QSize(16777215, 195))
        self.listView.setStyleSheet("QScrollBar:horizontal {\n"
"    height: 10px;\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    height: 10px;\n"
"    background-color: rgb(205,116,61);\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background-color: rgb(231, 128, 69);\n"
"}\n"
"\n"
"QScrollBar::handle:pressed {\n"
"    background-color: rgb(231, 128, 69);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal, QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar:left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"")
        self.listView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setProperty("showDropIndicator", False)
        self.listView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listView.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listView.setFlow(QtWidgets.QListView.LeftToRight)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Склад слитков"))
        self.label.setText(_translate("Dialog", "Свободные слитки"))
        self.label_2.setText(_translate("Dialog", "Слитки в работе"))
        self.label_3.setText(_translate("Dialog", "Запланированные слитки"))
