name: OCI

on:
  push:
    branches:
      - master
      - test_ci
  pull_request:
    branches:
      - master


jobs:
  linting:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8
        pip install -r requirements.txt
    #    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check
      run: |
        python --version
        python -m pylint --version
        python -m flake8 --version
  # - name: Lint with pylint
  #   run: |
  #     # stop the build if there are Python syntax errors or undefined names
  #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  # testing:
  #   runs-on: windows-latest

  # build:
  #   runs-on: windows-latest
  #   steps:
  #   - name: Set up Python 3.9
  #     uses: actions/setup-python@main
  #     # with:
  #     #   python-version: 3.9
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install PySide6 pyyaml cx_Freeze
  #   - name: Build
  #     run: |
  #       dir
